### ISSUE TITLE
SecurityPolicy should allow multiple port range separated by commas

### ISSUE THREAD

**Issue by zwtop** [smartxworks/lynx#127]
e.g.
```yaml
apiVersion: security.lynx.smartx.com/v1alpha1
kind: SecurityPolicy
metadata:
 name: security-policy
spec:
...
 egressRules:
   - name: egress01
     ports:
       - portRange: 10-22,80,8080-8082
...
```
